version: '3.1'
services:
  mongodb:
    image: mongo:3-stretch
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: reviews
  reviews:
    context: reviews/
    restart: always
    depends_on:
      - mongodb
  reviews:
    context: products/
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081