version: '3.1'
services:
  mongodb:
    image: mongo:3-stretch
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: reviews
  reviews:
    build: docker/reviews/
    restart: always
    depends_on:
      - mongodb
  products:
    build: docker/products/
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081